json.id product.id
json.name product.name
json.price product.price
json.images product.image_urls
json.description product.description
json.discounted product.discounted?
json.tax product.tax
json.total product.total
json.message "YO"
json.supplier_name product.supplier.name
json.categories product.categories
json.category_names product.category_names
